### ISSUE TITLE
大佬 关键字错误 无法运行了

### ISSUE THREAD

**Issue by ylj1314** [azwhikaru/auto_xueanquan#2]
Traceback (most recent call last):
  File "D:\RJDir\个人桌面\学安全2.0.py", line 403, in <module>
    doWorkUtil(username, password)
  File "D:\RJDir\个人桌面\学安全2.0.py", line 369, in doWorkUtil
    doHomework(courseId, UserId, webUrl, cityId, schoolId, classroomId, grade, gradeId)
  File "D:\RJDir\个人桌面\学安全2.0.py", line 178, in doHomework
    if(doSkillTest(courseId, UserID, ServerSide, cityCode, schoolId, classroom, grade)):
  File "D:\RJDir\个人桌面\学安全2.0.py", line 160, in doSkillTest
    isSkillTestSuccess = requestMsg ['success']
KeyError: 'success'
>>>

**Comment by huujiee** [comment]
courseId解析错误，getCourseId这个方法

**Comment by ylj1314** [comment]
这个用啥办法解决啊

**Comment by huujiee** [comment]
def getCourseId(url):
    cutUrl = url.split('li=')
    cutUrl = cutUrl[1].split('&')
    return cutUrl[0]

可以临时解决

**Comment by ylj1314** [comment]
收到 感谢🙏
