### ISSUE TITLE
求大神更新，AttributeError: 'NoneType' object has no attribute 'find'，

### ISSUE THREAD

**Issue by ionionyuan** [azwhikaru/auto_xueanquan#4]
运行后显示
- 正在解析任务列表...
= 获取到了 20 个任务

> 正在解析第 1/20 个任务 ===================
= 当前课程标题: 2023年中小学生（幼儿）平安暑假专项活动
= 当前课程链接: https://huodong.xueanquan.com/summer2023/index.html?require-un=true
= 当前课程类型: 寒暑假专题
= 当前课程完成情况: 未完成
+ 正在自动完成假期专题活动...
Traceback (most recent call last):
  File "C:\Users\IONION-学校\Desktop\auto_xueanquan-main\main.py", line 406, in <module>
    doWorkUtil(username, password)
  File "C:\Users\IONION-学校\Desktop\auto_xueanquan-main\main.py", line 378, in doWorkUtil
    doHolidaySpecial(holidayUrl, UserId, webUrl)
  File "C:\Users\IONION-学校\Desktop\auto_xueanquan-main\main.py", line 290, in doHolidaySpecial
    specialId = getspecialId(url)
  File "C:\Users\IONION-学校\Desktop\auto_xueanquan-main\main.py", line 234, in getspecialId
    return getSubStr(releaseData, "specialId: ", ",")
  File "C:\Users\IONION-学校\Desktop\auto_xueanquan-main\main.py", line 31, in getSubStr
    start_pos = s.find(start_str)
AttributeError: 'NoneType' object has no attribute 'find'

![微信截图_20230625140619](https://github.com/azwhikaru/auto_xueanquan/assets/27041699/53d6ccd0-51b9-439a-87d8-9daa49450143)

**Comment by wqh966** [comment]
我也是相同的问题，期待作者看到后更新，造福大家。

**Comment by lanmiemie** [comment]
你们可以用这个
xueanquan.archerfish1114.top

**Comment by wqh966** [comment]
> 你们可以用这个 xueanquan.archerfish1114.top

网站吗？打不开呀

**Comment by wqh966** [comment]
> 你们可以用这个 xueanquan.archerfish1114.top

这里下载的工具运行也报错了

**Comment by lanmiemie** [comment]
> > 你们可以用这个 xueanquan.archerfish1114.top
> 
> 这里下载的工具运行也报错了

报错什么？

**Comment by wqh966** [comment]
> 



> > > 你们可以用这个 xueanquan.archerfish1114.top
> > 
> > 
> > 这里下载的工具运行也报错了
> 
> 报错什么？

教师版的，以下是日志信息：
开始检测网络连通性...
正在获取该账号的信息-----
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "xueanquanhelperforteacher.py", line 973, in startmain
  File "xueanquanhelperforteacher.py", line 855, in main_page
  File "xueanquanapi.py", line 85, in teacher_get_schoolid
AttributeError: 'NoneType' object has no attribute 'xpath'

**Comment by wqh966** [comment]
> 



> > > 你们可以用这个 xueanquan.archerfish1114.top
> > 
> > 
> > 这里下载的工具运行也报错了
> 
> 报错什么？
原来你就是那安全教育平台助手源码放出的作者，有需要教师版账号测试啥的可直接联系我，WX号：wqh3966
