### ISSUE TITLE
PyCharm Community Edition运行报错咋回事？

### ISSUE THREAD

**Issue by jujue123456** [azwhikaru/auto_xueanquan#5]
Traceback (most recent call last):
  File "C:/Users/lly/Desktop/auto_xueanquan-main/main.py", line 406, in <module>
    doWorkUtil(username, password)
  File "C:/Users/lly/Desktop/auto_xueanquan-main/main.py", line 339, in doWorkUtil
    numOfWork = len(workListData)
TypeError: object of type 'int' has no len()

**Comment by wqh966** [comment]
应该是网站有升级，代码失效了，期待作者能早日更新，造福大家！
